using System;

namespace Extensions
{
	// Component type extension generated by Pega Robot Studio 19.1.75.0
	[OpenSpan.DynamicMembers.Extensions.ExtendTypeAttribute("System.Windows.Forms.TextBox, System.Windows.Forms")]
	public class TextBoxExtension : OpenSpan.ExpressTranslators.ExpressExtensionBase
	{
		public TextBoxExtension()
		{
		}
	}
}
