using System;

namespace Extensions
{
	// Component extension generated by Pega Robot Studio 19.1.75.0
	[OpenSpan.DynamicMembers.Extensions.ExtendComponentAttribute("UniversalWebAdapter-8D8DE50B28552EF\\WebPage-8D8E248A5F8C9E4")]
	public class ACMEwpSignInExtension : OpenSpan.ExpressTranslators.ExtensionBase
	{
		public ACMEwpSignInExtension()
		{
		}
	}
}
