using System;

namespace Extensions
{
	// Component type extension generated by Pega Robot Studio 19.1.75.0
	[OpenSpan.DynamicMembers.Extensions.ExtendTypeAttribute("OpenSpan.Adapters.Web.WebBase.Controls.WebPage, OpenSpan.Adapters.Web.WebBase")]
	public class WebPageExtension : OpenSpan.ExpressTranslators.ExtensionBase
	{
		public WebPageExtension()
		{
		}
	}
}
